# Generated by Django 3.1.7 on 2021-05-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210503_1531'),
        ('users', '0012_auto_20210503_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
