# Generated by Django 3.1.7 on 2021-05-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210503_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='status',
            field=models.CharField(default=0, max_length=256, null=True),
        ),
    ]
