# Generated by Django 3.1.7 on 2021-05-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210503_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='status',
        ),
    ]
