# Generated by Django 3.1.7 on 2021-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_provider_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='about',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default=0, max_length=256, null=True),
        ),
    ]
