# Generated by Django 3.1.7 on 2021-05-03 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210503_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 3, 18, 55, 45, 182844)),
        ),
        migrations.AlterField(
            model_name='request',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 3, 18, 55, 45, 183425)),
        ),
    ]
