# Generated by Django 3.1.7 on 2021-05-03 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210503_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 3, 18, 56, 19, 503599, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 3, 18, 56, 19, 504208, tzinfo=utc)),
        ),
    ]
