# Generated by Django 3.1.7 on 2021-05-04 18:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210503_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 4, 18, 26, 3, 51953, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='provider',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 4, 18, 26, 3, 51935, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 4, 18, 26, 3, 52512, tzinfo=utc)),
        ),
    ]
